---
title: "HW6"
author: "Ann Gould"
output:
  html_document:
    df_print: paged
---

```{r}
library(MASS)
library(ISLR)
library(leaps)
```
# 1 
```{r}
head(Boston)
?Boston

# a 
m_hat <- median(Boston$crim)
m_hat

# b
set.seed(12)
B <- 1000
bs_median <- rep(0,B)

n = dim(Boston)[1]
bootstrap_median <- c()

for (i in 1:B){
  index = sample(1:n,n,replace=TRUE)
	bootsample = Boston[index,]
 bootstrap_median[i] <-median(bootsample$crim)
}
bootstrap_median

se <- sqrt(sum((bootstrap_median-mean(bootstrap_median))^2)/(B-1))
se 

# c 
Y = rep(0,dim(Boston)[1])
Y[Boston$crim > m_hat] = 1

Boston$Y = Y
```

``` {r}

se <- 
se 
# d

log.train1 <- glm(Y~nox+age, data=Boston, family=binomial)
summary(log.train1)

# e 

# f leave one out cross validation
log.train2 <- glm(Y~nox+age+rad, data=Boston, family=binomial)
summary(log.train2)
```

# 2
```{r}

```


# 3
```{r}
set.seed(12)
data("College")
College
```

# 3a
```{r}

# i could write a function from the last hw
# but this is R. what is a user defined function anyways?
x_test <- data.frame()
x_train <- data.frame()
for (row in 1:nrow(College)) {
  if (row %% 5 == 0){
    x_test <- rbind(College[row,], x_test)
  }
  else{
    x_train <- rbind(College[row,], x_train)
  }
}

x_train = na.omit(x_train)
x_test = na.omit(x_test)


y_test <- x_test$Apps
y_train <- x_train$Apps


x_train$Apps = NULL
x_test$Apps = NULL
# randomize? 

```

```{r}
# 3b 
linear_model <- lm(y_train ~ x_train)
foo <- predict(linear_model, x_test)

# mse_linear <- mean((ridge.pred-test)^2)/length(test)

ridge.train = glmnet(X[train,],Y[train],alpha=0,lambda=lambdagrid)
predict(ridge.train,type='coefficients',s=bestlambda)[1:20,]

ridge.pred = predict(ridge.train,s=bestlambda,newx=X[test,])
mean((ridge.pred-Y.test)^2)/length(test)
```

